# Default values for my-complex-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: kanatohodets/whoami
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: prod
  type: LoadBalancer
  externalPort: 80
  internalPort: 3000
